uploads = []
outputs = []

[[generated]]
id = "le2A2bT7kQqfVKM-GhkIl"
uri = "file://attached_assets/hizmet_ev_temizligi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "8sE7gFEvzeTO_GtOdK7Em"
uri = "file://attached_assets/hizmet_ofis_temizligi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZNDzHy_UfbrKUnI7bC1qs"
uri = "file://attached_assets/hizmet_insaat_sonrasi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "nLxCtukKy1zpSrSq8e27b"
uri = "file://attached_assets/hizmet_detay_temizlik.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ABbAgRmHdHQCfI7xt7IEr"
uri = "file://attached_assets/hizmet_saygi.png"
type = "image"
title = "generated_image"

[[generated]]
id = "YmZD4F_Wp1px2vTducrtA"
uri = "file://attached_assets/akademi_hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_B_RxkA6yKQx4nY2_wdJ8"
uri = "file://attached_assets/akademi_hijyen.png"
type = "image"
title = "generated_image"

[[generated]]
id = "X3tegYoIwZYflKMfMOAjZ"
uri = "file://attached_assets/akademi_sertifika.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UHAlkUKJ4b84ufXsJGqB8"
uri = "file://attached_assets/akademi_egitim.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RIP5LjcTtMAZajcoq2jfB"
uri = "file://attached_assets/kurumsal_hero.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TUxtu8QrwGp6ImRfbbeZ1"
uri = "file://attached_assets/kurumsal_kalite.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vg3w2uNIoEdRxWOWok9sA"
uri = "file://attached_assets/kurumsal_sozlesme.png"
type = "image"
title = "generated_image"
